name:                XCodeGen
version:             0.1.0.0
github:              "xstater/XCodeGen"
license:             MIT
author:              "xstater"
maintainer:          "166224@163.com"
copyright:           "xstater 2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xstater/XCodeGen#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- mtl
- text
- hint
- optparse-applicative

library:
  source-dirs: src

executables:
  xcg:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - XCodeGen

